### ISSUE TITLE
AWS Developer Getting Started Question

### ISSUE THREAD

**Issue by leighanneduvall** [ryanmurakami/pizza-luvrs#1]
This may not be the correct way of asking a question regarding your Pluralsight course. If not, could you tell me how best to do that? I'm following your course and I successfully created the EC2 instance and got the pizza-luvrs app running on my local box. Now, I'm trying to do the part where I SSH it up to the EC2 instance, but I have a Windows machine. You mention using Putty. I've used that before. However, I don't know if the chmod 400 command that you told us to run against the pizza-keys.pem is supposed to work on Windows or if both that command and the SSH -i command are for Mac users only. Can you help?

**Comment by leighanneduvall** [comment]
I was able to download Putty and make this work with the help of a lot of Google searching. I did not have to use the chmod 400 command.

**Comment by ryanmurakami** [comment]
@leighanneduvall Glad you figured it out! You can ask questions here or in the Pluralsight comments if you need anything else.
