### ISSUE TITLE
Login Issue in local 

### ISSUE THREAD

**Issue by satishthamarana** [ryanmurakami/pizza-luvrs#10]
Hi Ryan,

Thanks for your tutorial really very helpful....

my issue was , when i make use of your code in my local and run on npm , i tried to access the pizza luvrs
app but unable to register the user nor login 
do i missed any thing ?  
i even tried with ryan/username   pass/password 

regards
Satish

**Comment by ryanmurakami** [comment]
Hi Satish,

Hmm... that is odd. On the command line, does the application print any errors out? It should work locally with no issues. Check line 72 in `plugins.js`. That is the line that creates the users with username and password in memory. Maybe put a `console.log` statement there to make sure that function is executed? 

Let me know what you find out.
Thanks!
Ryan

**Comment by satishthamarana** [comment]
Hi Ryan ,

Thanks for your reply , it's working fine , as I took the latest from the
plural videos , and it's working fine , don't know from git I my downloads
missed some files may be ...

Regards
Satish Thamarana

On 15 Sep 2017 10:55 a.m., "Ryan Lewis" <notifications@github.com> wrote:

Hi Satish,

Hmm... that is odd. On the command line, does the application print any
errors out? It should work locally with no issues. Check line 72 in
plugins.js. That is the line that creates the users with username and
password in memory. Maybe put a console.log statement there to make sure
that function is executed?

Let me know what you find out.
Thanks!
Ryan

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ryanmurakami/pizza-luvrs/issues/10#issuecomment-329684768>,
or mute the thread

**Comment by stevefuzzy** [comment]
I'm experiencing a similar issue.  I did a get clone of the repository.  It comes up fine, but if I try register a new user, the console generates the following stacktrace:
`Debug: internal, implementation, error
    TypeError: The "digest" argument is required and must not be undefined
    at pbkdf2 (crypto.js:694:11)
    at Object.exports.pbkdf2 (crypto.js:682:10)
    at generateKey (/home/ec2-user/pizza/node_modules/hapi/node_modules/iron/lib/index.js:129:16)
    at generateSalt (/home/ec2-user/pizza/node_modules/hapi/node_modules/iron/lib/index.js:124:16)
    at generate (/home/ec2-user/pizza/node_modules/hapi/node_modules/iron/lib/index.js:110:20)
    at Object.exports.generateKey (/home/ec2-user/pizza/node_modules/hapi/node_modules/iron/lib/index.js:165:5)
    at Object.exports.encrypt (/home/ec2-user/pizza/node_modules/hapi/node_modules/iron/lib/index.js:174:13)
    at Object.exports.seal (/home/ec2-user/pizza/node_modules/hapi/node_modules/iron/lib/index.js:283:13)
    at Object.internals.encode (/home/ec2-user/pizza/node_modules/hapi/node_modules/statehood/lib/index.js:468:14)
    at Object.exports.prepareValue (/home/ec2-user/pizza/node_modules/hapi/node_modules/statehood/lib/index.js:433:15)
`
In addition, for failed logins, the app returns JSON, not html

**Comment by ryanmurakami** [comment]
Hi @stevefuzzy, 

I think this is a result of some changes in newer versions of Node.js. Can you check your version to see if it's 6.x? I'm thinking it's actually either 8.x or 9.x, which changed some things in the `crypto` module. Can you try downgrading your version of Node.js to 6.x and let me know if you're still having the same issue?

Thanks,
Ryan

**Comment by stevefuzzy** [comment]
Thanks for the quick reply!

Yes, it's most definitely because I'm running with the latest node (version 8.9.4).
I'd rather not downgrade, because I need it for other things.
The problem is with Hapi.  Tried updating that to the latest, but there was a major breaking change when they went to v17, so was able to make it work by using hapi v16.6.2, and hapi-auth-cookie v7.0.0.
I still get some debug warning/error in the console:
`Debug: internal, implementation, error
    Error: Request logging is disabled
    at Object.exports.assert (C:\Dev\aws\pizza\node_modules\hoek\lib\index.js:740:11)
    at internals.Request.getLog (C:\Dev\aws\pizza\node_modules\hapi\lib\request.js:291:10)`

But at least I got it to work.
Ran into other issues, for which I will open separate issues.

**Comment by tomschinelli** [comment]
For me this worked (windows): 

1. ```Download``` the node.exe https://nodejs.org/download/release/v6.13.1/win-x64/
2. ```copy``` node.exe to your project
3. run ```node.exe index.js```

I only recommend this to verfy, if the save to s3 method works.

**Comment by cesammaz** [comment]
Is pretty odd, but for me, login does not work locally but works when deployed in EC2.  Saving and retrieving from S3 works very well as well.  I assume that the versioning I have locally makes the difference, but I don't want to downgrade locally.
