### ISSUE TITLE
make pizza endpoints broken

### ISSUE THREAD

**Issue by crobinson42** [ryanmurakami/pizza-luvrs#12]
Node.js version 6.2.2
OSX

Running npm install then npm start, logging in with "ryan" / "pass" > click "make a pizza" > click "create" > redirects to /pizza with a json message 404:
![screenshot 2017-12-09 08 17 01](https://user-images.githubusercontent.com/5973579/33797259-9e39fcb0-dcb9-11e7-8bfe-e9ea6e5a8961.png)

The console shows this message:
![screenshot 2017-12-09 08 17 08](https://user-images.githubusercontent.com/5973579/33797262-a6e51bc4-dcb9-11e7-8ebf-e6e9a098e822.png)

**Comment by crobinson42** [comment]
Haha...well, if you don't put in a pizza name before clicking create you will get a 404! 

So, everything is working fine, sorry @ryanmurakami user error!

**Comment by ryanmurakami** [comment]
Hi @crobinson42! Glad you got it working!
