### ISSUE TITLE
Warning deprecated message

### ISSUE THREAD

**Issue by JaviRpo** [ryanmurakami/pizza-luvrs#16]
There are warning messages when I run the app
![image](https://user-images.githubusercontent.com/8562436/38004030-fd4411a0-31ff-11e8-9bf2-c8ec0198c3a2.png)

**Comment by ryanmurakami** [comment]
@JaviRpo Thanks for reporting this! This is likely just a dependency that is using something that will soon be deprecated. I wrote this program with Node.js v6, and you're likely running v8 or v9, which has the deprecation. Everything should work fine.
