### ISSUE TITLE
Issue starting pizza-luvrs

### ISSUE THREAD

**Issue by MasterSolidX** [ryanmurakami/pizza-luvrs#2]
Found an error while working on the Pluralsight training video. 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle pizza-luvrs@1.0.0~prestart: pizza-luvrs@1.0.0
6 silly lifecycle pizza-luvrs@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle pizza-luvrs@1.0.0~start: pizza-luvrs@1.0.0
8 verbose lifecycle pizza-luvrs@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle pizza-luvrs@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/mastersolidx/Downloads/pizza-luvrs/node_modules/.bin:/root/perl5/bin:/root/perl5/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/mastersolidx/.local/bin:/home/mastersolidx/bin
10 verbose lifecycle pizza-luvrs@1.0.0~start: CWD: /home/mastersolidx/Downloads/pizza-luvrs
11 silly lifecycle pizza-luvrs@1.0.0~start: Args: [ '-c', 'node index.js' ]
12 silly lifecycle pizza-luvrs@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle pizza-luvrs@1.0.0~start: Failed to exec start script
14 verbose stack Error: pizza-luvrs@1.0.0 start: `node index.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid pizza-luvrs@1.0.0
16 verbose cwd /home/mastersolidx/Downloads/pizza-luvrs
17 error Linux 3.10.0-327.36.3.el7.x86_64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.9.1
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error pizza-luvrs@1.0.0 start: `node index.js`
22 error Exit status 1
23 error Failed at the pizza-luvrs@1.0.0 start script 'node index.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the pizza-luvrs package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs pizza-luvrs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls pizza-luvrs
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by MasterSolidX** [comment]
Never mind. I needed to run the "npm install" 
Thanks.

**Comment by ryanmurakami** [comment]
Glad you figured it out!
