### ISSUE TITLE
Am having this Error below while trying to deploy pizza-lurs App into Ecs instance

### ISSUE THREAD

**Issue by workfast108** [ryanmurakami/pizza-luvrs#21]
Dear Ryan,

Thank You for your wonderful project, actually am having issue while trying to Deploy your application 
I successfully run it on my local host. but here is the error am getting while trying to deploy it.. 
the application.

**Comment by workfast108** [comment]
Dear Ryan,

Thank You for your wonderful project, actually am having issue while trying to Deploy your application
I successfully run it on my local host. but here is the error am getting while trying to deploy it..
the application. am using windows 10 i google and try different version of npm, on the aws EC2 instance, nothing seems..to work. please advice on what to do.Thank You 
![pizza](https://user-images.githubusercontent.com/24754100/49633515-97a67980-fa1f-11e8-81b6-91a6bc3fbc4b.PNG)

**Comment by ryanmurakami** [comment]
Sorry for the late reply. It appears that there is nothing in the `pizza-luvrs` directory. Could you run an `ls` and tell me the output?

**Comment by workfast108** [comment]
it is fixed, you are absolutely correct, i fixed it long ago, thank you

**Comment by ryanmurakami** [comment]
Great!
