### ISSUE TITLE
npm install in instance error

### ISSUE THREAD

**Issue by karlarvan** [ryanmurakami/pizza-luvrs#23]
Hi! Whenever I try npm install inside the instance into a ssh connection this error occurs:

npm WARN pizza-luvrs@1.0.0 No description
npm WARN pizza-luvrs@1.0.0 No repository field.

**Comment by ryanmurakami** [comment]
Hi @karlarvan,

Don't worry, this is just a warning, not an error. I'll fix it so this warning never shows.

Thanks for opening the issue!

**Comment by karlarvan** [comment]
Hi Ryan,

Thanks for answering. After installing, I tried to use npm start but it says that the start script is missing. Thanks for helping out!

Karl
