### ISSUE TITLE
npm start

### ISSUE THREAD

**Issue by karlarvan** [ryanmurakami/pizza-luvrs#24]
Hi Ryan! npm start gives me an error that a start script is missing. Please help me out, thanks!

**Comment by ryanmurakami** [comment]
Hi @karlarvan, that's odd. I see it in the `package.json` file right here: https://github.com/ryanmurakami/pizza-luvrs/blob/master/package.json#L8. Does the `package.json` where you are running `npm start` match that one?

**Comment by karlarvan** [comment]
Hi Ryan, the issue has already been resolved. Thank you very much!
