### ISSUE TITLE
node index.js fails on windows10

### ISSUE THREAD

**Issue by Airedyver** [ryanmurakami/pizza-luvrs#25]
After getting pizza-luvrs up through a local host, which worked, I got an error after npm start when trying to get AWS up and running on a server. This is the error in full: 

> pizza-luvrs@1.0.0 start /home/ec2-user/pizza-luvrs
> node index.js

/home/ec2-user/pizza-luvrs/node_modules/hapi/lib/server.js:274
    async inject(options) {
          ^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/pizza-luvrs/node_modules/hapi/lib/index.js:3:16)

npm ERR! Linux 4.14.77-70.59.amzn1.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! pizza-luvrs@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pizza-luvrs@1.0.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pizza-luvrs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pizza-luvrs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pizza-luvrs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/pizza-luvrs/npm-debug.log

I originally had an error at the local host level, but following a previous post I was able to reinstall pizza-luvrs and NOT use npm audit to start it up. Any ideas on how to fix this?

**Comment by ryanmurakami** [comment]
Hi @Airedyver! Sorry you're having trouble. The specific error is because the `async` keyword wasn't implemented in Node.js until version 8 and it looks like you're using version 6. That version of Node.js should be fine with all of the dependencies included, but it looks like it's dying on the hapi dependency. 

So, long story short, to fix it, I think you need to downgrade your hapi version to version 13.5.3. Do this by running: `npm install hapi@13.5.3`. Then try running `npm start` and let me know what happens.

Good luck!

**Comment by Airedyver** [comment]
That worked! Thank you so much!
