### ISSUE TITLE
Error 500 for user creation & login module

### ISSUE THREAD

**Issue by TonyL-AlayaCare** [ryanmurakami/pizza-luvrs#38]
Something seems to have changed in the dependencies that causes the user creation / login module to crash. I've replicated the issue both on my local Windows machine (where node.js 12.x was freshly installed) and also on Amazon Linux 2.

`C:\Users\tonyk\Downloads\pizza-luvrs-master>npm  -v`
`6.12.1`

`C:\Users\tonyk\Downloads\pizza-luvrs-master>node  -v`
`v12.13.1`

`C:\Users\tonyk\Downloads\pizza-luvrs-master>npm  start`

`> pizza-luvrs@1.0.0 start   C:\Users\tonyk\Downloads\pizza-luvrs-master`
`> node index.js`

`Server running at: http://XPS15:3000`

At this point, I create a user with username "user1" and password "asdfqwerty" in the web UI, and get the following in the terminal:

`Debug: internal, implementation, error`
`      TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must   be one of type string, Buffer, or ArrayBuffer. Received type undefined`
`      at Function.byteLength (buffer.js:705:11)`
`      at new internals.MemoryCacheEntry   (C:\Users\tonyk\Downloads\pizza-luvrs-master\node_modules\@hapi\catbox-memory\lib\index.js:223:36)`
`      at module.exports.internals.Connection.set   (C:\Users\tonyk\Downloads\pizza-luvrs-master\node_modules\@hapi\catbox-memory\lib\index.js:168:26)`
`      at module.exports.set   (C:\Users\tonyk\Downloads\pizza-luvrs-master\node_modules\@hapi\catbox\lib\client.js:91:31)`
`      at module.exports.internals.Policy.set   (C:\Users\tonyk\Downloads\pizza-luvrs-master\node_modules\@hapi\catbox\lib\policy.js:298:31)`
`      at postUser   (C:\Users\tonyk\Downloads\pizza-luvrs-master\handlers\user.js:9:30)`
`      at processTicksAndRejections (internal/process/task_queues.js:93:5)`
`      at async module.exports.internals.Manager.execute   (C:\Users\tonyk\Downloads\pizza-luvrs-master\node_modules\@hapi\hapi\lib\toolkit.js:45:28)`
`      at async Object.internals.handler   (C:\Users\tonyk\Downloads\pizza-luvrs-master\node_modules\@hapi\hapi\lib\handler.js:46:20)`
`      at async exports.execute   (C:\Users\tonyk\Downloads\pizza-luvrs-master\node_modules\@hapi\hapi\lib\handler.js:31:20)`

Video screenshot of the steps to reproduce attached.
[pizzaluvrs-err500.zip](https://github.com/ryanmurakami/pizza-luvrs/files/3889792/pizzaluvrs-err500.zip)

I suspect this is an issue with updated dependencies because it worked just fine 2 months ago when I followed the Pluralsight video.

**Comment by ryanmurakami** [comment]
Hi @TonyL-AlayaCare! Thanks for sharing all the info. I did indeed miss this with the update. @rubenccdev PRed a fix for this and I just merged it, so give it a shot now. It seems to be working for me.
