### ISSUE TITLE
HTTP/S protocols stored on postgresql

### ISSUE THREAD

**Issue by mdelapenya** [ryanmurakami/pizza-luvrs#4]
Hi Ryan, I'm following this amazing course on Pluralsight. Congrats for your preparation and materials :)

I noticed that after adding the code for postgresql, the protocol of a new pizza's S3 URL holds the protocol, as you can see in this picture.

<img width="1437" alt="screen shot 2017-04-05 at 19 39 55" src="https://cloud.githubusercontent.com/assets/951580/24718832/c1838c08-1a37-11e7-9a24-fedbbdf24771.png">

It's not a severe problem at all, but just for letting you know :)

Cheers!

**Comment by ryanmurakami** [comment]
Thanks for letting me know! I appreciate it!
