### ISSUE TITLE
5 high security issues from npm audit

### ISSUE THREAD

**Issue by gruffeety** [ryanmurakami/pizza-luvrs#45]
I told it "npm audit fix --force" & then "npm start" failed (due to the breaking changes I was warned about, I assume). 

Side note (nothing to do with this issue, but just wanna say): your pluralsight course is great so far. Thanks for it!

**Comment by ryanmurakami** [comment]
Hi Gruffeety, 

Yep, I'll be working on an update for this code soon, but there are some newer breaking changes. I'd suggest not fixing the security issues for the demo purposes. As long as you aren't trying to put pizza luvrs into production, you should be fine. 

Thanks for the kind words about the course!
Ryan

**Comment by gruffeety** [comment]
closing this issue, even though you may not have addressed the npm audit complaints yet. Thanks for the response.
