### ISSUE TITLE
image and styles not showing up after adding the CORS configuration

### ISSUE THREAD

**Issue by rahmt** [ryanmurakami/pizza-luvrs#46]
Hi, 
I do not see any image when i'm doing the npm start command and hitting the localhost:3000.
![image](https://user-images.githubusercontent.com/40688424/81472923-a565bd00-9218-11ea-961a-a46a07c64f6d.png)

**Comment by ryanmurakami** [comment]
Looks like the images and css aren't loading. What is the output in your command line when you run it?

**Comment by rahmt** [comment]
Hi Ryan,
The command line shows the server to be up and running.
![image](https://user-images.githubusercontent.com/40688424/81485531-58f79d00-926b-11ea-83f0-f1087ba93fec.png)

**Comment by ryanmurakami** [comment]
Hmm... okay. Try opening the developer tools in your browser and see if the css files are loading. Also, check the browser console and see if there are any JavaScript errors.

**Comment by rahmt** [comment]
I see this error in the dev tools for my browser:
stylesheet.css:1 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by ryanmurakami** [comment]
Which browser are you using? Could you try another one, because I can't repro this and it seems like it might have something to do with your local machine.

**Comment by rahmt** [comment]
i am using chrome and even I.E didn't work..

**Comment by ryanmurakami** [comment]
Hi @rahmt, I know it's been a while, but I've published an update to the course and hopefully it'll fix this issue.
