### ISSUE TITLE
Unable to connect to postgres created on AWS RDS

### ISSUE THREAD

**Issue by kirankomirishetty** [ryanmurakami/pizza-luvrs#48]
Hi Ryan, 

Mock pizzas are not getting inserted to postgres on rds after adding the pizzaStore.js file.

I tried to add the logs and the whole functionality is working as excepted but it takes for ever for database insertion. 

I dont even get any error message. I am attaching my files for reference.
[pizza.txt](https://github.com/ryanmurakami/pizza-luvrs/files/4684914/pizza.txt)
[pizzaStore.txt](https://github.com/ryanmurakami/pizza-luvrs/files/4684915/pizzaStore.txt)

FYI, I can connect to database and created a table using database tool.

**Comment by ryanmurakami** [comment]
Hi @kirankomirishetty,

Sorry you're having this issue! Another learner had the same issue but was able to resolve it by using these dependency versions. Can you try those out and see if that fixes things?

"pg": "8.1.0",
"pg-hstore": "2.3.3",
"sequelize": "5.13.0"

**Comment by kirankomirishetty** [comment]
Thanks Ryan for quick reply, that change did worked for me. I was trying it by bumping just the sequelize version.
