### ISSUE TITLE
Error in login

### ISSUE THREAD

**Issue by angelllllll** [ryanmurakami/pizza-luvrs#5]
Hi,

After i have launched the ec2 instance with the code and tried to login with my account(not root)
the response code of 401 is displayed.

Whereas it works fine with root credentials.

Kindly help

**Comment by ryanmurakami** [comment]
Hi @angelllllll 

Sorry you're having trouble!

Hmm... creating users on your EC2 instance is a little different than on your account. The main reason is that there is no real connection between users in IAM and users on your instance. 

I found this tutorial which does replicate IAM users onto an EC2 instance, but it is a little heavy: https://cloudonaut.io/manage-aws-ec2-ssh-access-with-iam/

Let me know if that answers your question!

Thanks,
Ryan

**Comment by angelllllll** [comment]
Thanks a lot for your reply and your tutorials are great !!!

Will try the option mentioned .


Regards
Angel
