### ISSUE TITLE
Unable to upload the files to S3 from windows using AWS command

### ISSUE THREAD

**Issue by RamaBo** [ryanmurakami/pizza-luvrs#51]
I am getting the following error  after copy command (xxxx denotes my 
PS C:\ramar\aws\pizza-luvrs> aws s3 cp ./assets/js s3://pizza-luvrs-xxxx/js --recursive --exclude ".DS_Store"
upload failed: assets\js\make.js to s3://pizza-luvrs-xxxx/js/make.js An error occurred (SignatureDoesNotMatch) when calling the PutObject operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
I did reset my aws password and not sure if that caused the issue. do I need to regenerate the key again because of password change? Is that the issue?

**Comment by ryanmurakami** [comment]
Hi @RamaBo, SignatureDoesNotMatch has often had something to do with the aws config. Can you try resetting your key and secret and adding it back to the aws config? I don't think the password change had anything to do with it, but go ahead and give it a try anyways.

**Comment by RamaBo** [comment]
Hi Ryanmurakami/Pizza-Luvrs

That is what I did and it worked. Also, I was getting 400 error when I try
to create pizza. I can create a new user and continue but when I login it
fails. From the blog it appears something to do with browser cache. I just
ignored that issue and continued with the training.

Rama Boggarapu

Thanks a bunch,

**Comment by ryanmurakami** [comment]
Glad to hear it worked!
