### ISSUE TITLE
npm error when setting up EC2 instance of pizza-luvrs

### ISSUE THREAD

**Issue by mtraskowsky** [ryanmurakami/pizza-luvrs#53]
In the pluralsight course in the "Connecting to an EC2 Instance" video, I follow the steps and clone the repo to my laptop. Then when I try to run the program, I get these errors: 

![image](https://user-images.githubusercontent.com/46056263/86047703-ec9c4d00-ba14-11ea-9abe-0568c6b380f2.png)

**Comment by fiuzaB** [comment]
I had the same problem. To fix it, just update your node: https://nodejs.org/en/

**Comment by mtraskowsky** [comment]
@fiuzaB that worked perfectly. Thank you!
