### ISSUE TITLE
npm packages

### ISSUE THREAD

**Issue by junior231** [ryanmurakami/pizza-luvrs#56]
Hi,

I installed the npm package and tried to run it and got this error.

Server running at: http://LAPTOP-PD0QR6FI:3000
{ SequelizeHostNotFoundError: getaddrinfo ENOTFOUND pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com:5432
    at connection.connect.err (C:\Users\16478\Desktop\pizza-luvrs\node_modules\sequelize\lib\dialects\postgres\connection-manager.js:173:24)
    at Connection.connectingErrorHandler (C:\Users\16478\Desktop\pizza-luvrs\node_modules\pg\lib\client.js:191:14)
    at Connection.emit (events.js:198:13)
    at Connection.EventEmitter.emit (domain.js:448:20)
    at Socket.reportStreamError (C:\Users\16478\Desktop\pizza-luvrs\node_modules\pg\lib\connection.js:72:10)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'SequelizeHostNotFoundError',
  parent:
   { Error: getaddrinfo ENOTFOUND pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com:5432
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com',
     host: 'pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com',
     port: 5432 },
  original:
   { Error: getaddrinfo ENOTFOUND pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com:5432
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com',
     host: 'pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com',
     port: 5432 } }

**Comment by ryanmurakami** [comment]
Hi @junior231, 

In the past, this was because of a mismatch with dependency versions. Can you tell me what version it shows for the `sequelize` dependency in the `package.json` file. Also, what version of node are you running? And finally, are you able to connect to the database with some kind of client? (postico / pgAdmin)

Thanks,
Ryan

**Comment by junior231** [comment]
Hi,

"sequelize": "5.13.0"
node version: "6.14.7"

No, unfortunately i am unable to connect to the database with postico / pgAdmin

Thanks,
Collins

**Comment by ryanmurakami** [comment]
Hi Collins,

Ah, okay. So I'm thinking there maybe an issue with the dependencies and node version, but it's more important that you can connect from a postgres client. There are four things you should check to try and connect:
- Ensure the database is running in RDS
- Ensure the "Public Availability" option is checked for the database (https://stackoverflow.com/questions/22866490/how-do-i-change-the-publicly-accessible-option-for-amazon-rds)
- Ensure the security group for the database gives access to anywhere for port 5432
- Ensure your firewall isn't blocking 5432 (this sometimes happens for a work connection)

Check those four things and try connecting again from the client. Once you can connect from the client, then you'll try checking the code again.

**Comment by junior231** [comment]
Hi Ryan,

I started the AWS Developer: Getting started course on Pluralsight and i have been following the video and installed npm as instructed, but when i did the "npm start" it gave me the error. Everything i know about the AWS platform i learnt from following the instructions in the video. 

All i have done prior to getting the error, was setting up a VPC and an EC2 instance. The instruction in the video asked to enter port 3000 in the rules for the Security Group which i did. I have added port 5432 as well and i'm still getting this error -

  name: 'SequelizeHostNotFoundError',
  parent:
   { Error: getaddrinfo ENOTFOUND pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com:5432
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com',
     host: 'pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com',
     port: 5432 },
  original:
   { Error: getaddrinfo ENOTFOUND pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com:5432
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
     errno: 'ENOTFOUND',
     code: 'ENOTFOUND',
     syscall: 'getaddrinfo',
     hostname: 'pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com',
     host: 'pizza-db.cc56pwsgbrsv.us-west-2.rds.amazonaws.com',
     port: 5432 } }

I also tried installing the latest version of Sequelize with "npm i sequelize" and still got the error.  In the video after "npm start" the "pizza-luvrs" app shows up in localhost:3000 but it doesn't for me.  

Looking forward to your timely response as always.

Collins

**Comment by ryanmurakami** [comment]
Hi Collins,

Have you reached the part of the course that has you set up your database in RDS? What code are you using? It sounds like you may be using code that is modified beyond the part you're watching in the course.

Ryan

**Comment by junior231** [comment]
Hi Ryan,

I am in the "Getting inside the Virtual Machine with EC2 and VPC" module and i just created an EC2 instance and the next step is connecting to an EC2 instance.

The instructions in the video asks us to download the "pizza-lurvs" app from Github or the exercise files in the course. I have tried both methods and after installing the npm package as directed in the video, the next step is to get the app up and running in the local host with "npm start", and that's where i keep getting the error. 

The module with setting up the database in RDS comes up way later in the course, and i can't get things going without first connecting to the EC2 instance according to the video.

I haven't made any changes to the code in the "pizza-luvrs" app after i cloned it from Github and downloaded the exercise files.

Thanks once again.
Collins

**Comment by ryanmurakami** [comment]
Hi Collins,

Okay, so it looks like somehow the code you're using is from later on in the course. If you clone this repository and then navigate to it in your command line, run `npm install` and then `npm start`, tell me what happens. The error that you are currently getting is coming from code that is not in this repo, it's from the exercise files. Let me know what happens when running the code from this repo.

Ryan

**Comment by junior231** [comment]
Hi Ryan,

I just cloned the repo and did an npm install and npm start and now i seem to be getting a different error now - 

$ npm start

> pizza-luvrs@1.0.0 start C:\Users\16478\Desktop\pizza-luvrs
> node index.js

C:\Users\16478\Desktop\pizza-luvrs\node_modules\@hapi\hapi\lib\core.js:51
    actives = new WeakMap();                                                   /                                                                                                                / Active requests being processed
            ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\16478\Desktop\pizza-luvrs\node_modules\@hapi                                                                                                                \hapi\lib\server.js:9:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pizza-luvrs@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pizza-luvrs@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\16478\AppData\Roaming\npm-cache\_logs\2020-08-13T00_17_01_                                                                                                                962Z-debug.log

The Sequelize error seems to be gone and now this shows up...

Collins

**Comment by ryanmurakami** [comment]
Hi Collins, 
Are you still on Node.js version 6.x? That might be the issue. Can you install version 12 and try again?

Thanks,
Ryan

**Comment by junior231** [comment]
Hi Ryan,

I installed the latest version of node.js and that finally solved the issue.

Thank you once for your assistance.

Collins

**Comment by ryanmurakami** [comment]
Awesome! Let me know if you run into any other issues!
