### ISSUE TITLE
Image and name not displayed

### ISSUE THREAD

**Issue by angelllllll** [ryanmurakami/pizza-luvrs#6]
Hello Ryan,

When the code is modified via SDK and i tried to create a new pizza , i see that the image is blank and also name of the pizza is shown as ${name}.png in the console.

I am not sure why and also unable to figure it out.

Regards
Angel

**Comment by angelllllll** [comment]
And also after this just to verify i login to my instance and try to open it via ip:3000 and even this does not open and gets timed out.

I expected ip : 3000 to open as it is no where related to the sdk changes which i have done till now.

**Comment by ryanmurakami** [comment]
Hi @angelllllll,
Could you post some more detailed log data or give more details?
Thanks!
Ryan

**Comment by angelllllll** [comment]
<img width="1250" alt="screen shot 2017-04-30 at 11 40 45 pm" src="https://cloud.githubusercontent.com/assets/27988757/25573993/f291dc34-2dfe-11e7-8d75-344235a5c1e9.png">
<img width="809" alt="screen shot 2017-04-30 at 11 41 04 pm" src="https://cloud.githubusercontent.com/assets/27988757/25573996/f6ce8d24-2dfe-11e7-9448-6899bae9ee0e.png">
<img width="1057" alt="screen shot 2017-04-30 at 11 41 15 pm" src="https://cloud.githubusercontent.com/assets/27988757/25574000/fb05d988-2dfe-11e7-827c-07bcbcc84dc2.png">

**Comment by angelllllll** [comment]
As told earlier , the images display like this and name that i have created does not show up rather ${name} gets printed.

**Comment by angelllllll** [comment]
And also when i login to my ec2 instance and try to launch after performing the code changes in SDK it says timed out.

<img width="607" alt="screen shot 2017-04-30 at 11 43 24 pm" src="https://cloud.githubusercontent.com/assets/27988757/25574039/50f6e9b8-2dff-11e7-8294-a18df0c7b71d.png">
<img width="1218" alt="screen shot 2017-04-30 at 11 45 58 pm" src="https://cloud.githubusercontent.com/assets/27988757/25574045/54d785ce-2dff-11e7-8f51-3fda6518c937.png">

**Comment by sameerhashmi** [comment]
Hi Ryan, I am having the same problem. Images in S3 beign saved as "${name}.png"

**Comment by sameerhashmi** [comment]
Resolved the issue. In imageStoreS3.js:

earlier: Key: 'pizzas/${name}.png',
fixed:Key: `pizzas/${name}.png`,

The difference was between the " ' " and " ` " character.
