### ISSUE TITLE
Can't connect to RDS with Sequelize neither pg

### ISSUE THREAD

**Issue by rcasca** [ryanmurakami/pizza-luvrs#62]
Hi all. I have created my postgres instance and I can connect with DBeaver (GUI) without any issue, but when I try to connect with Squelize or directly with pg node package is not working.

can anyone help me?

I tried openning the inbound rule with 0.0.0.0/0 but this is not the problem. As I said before, with my GUI client I have no issue.

Thanks.

**Comment by ryanmurakami** [comment]
Hi @rcasca,

Sounds like the security group is correct, like you said. Are you getting any error when the code tries to connect?

Thanks,
Ryan

**Comment by rcasca** [comment]
No error, the console stay:
`
λ npm start

> pizza-luvrs@1.0.0 start C:\Users\xxxx\Documents\AWS Developer Certificate\pizza-luvrs
> node index.js

Server running at: http://Laptop-LT67856:3000
`
and this console.log never appears
`
Pizza.sync().then(() => {
  console.log("postgres connection ready");
});
`

**Comment by ryanmurakami** [comment]
Try swapping the `Pizza.sync` code for this:
```
Pizza.sync().then(() => {
console.log('postgres connection ready')
}).catch(e => console.error(e))
```
I think it may be throwing an error and just not showing it.

**Comment by rcasca** [comment]
Nop, it's not working and not showing any error. It stays as before :(

Even I have try with the downloaded code from pluralsight and I changed only host and password in pizzaStore.js file and get the same issue.

**Comment by ryanmurakami** [comment]
Hmm... Can you try adding a `console.log('Before Pizza.sync')` on the line above `Pizza.sync` to make sure it's even running that code.

**Comment by rcasca** [comment]
Sure, I did it and this console.log appears:

> npm start
> pizza-luvrs@1.0.0 start C:\Users\xxx\Documents\AWS Developer Certificate\pizza-luvrs
> node index.js
>Before Pizza.sync
>Server running at: http://Laptop-LT67856:3000

Thanks. I'm going to try with an earlier postgres version also.

**Comment by ryanmurakami** [comment]
Okay, try matching the dependency versions with what's in the package.json in this repo. It could be a mismatch between `sequelize` and `pg` versions.

**Comment by rcasca** [comment]
:) the solution was easier, I update the versions of pg and sequelize and start working well.

>   "pg": "^8.5.1",
>    "sequelize": "6.3.5"

Thanks for your help.

Rafa.

**Comment by ryanmurakami** [comment]
Awesome! Glad to hear you figured it out!
