### ISSUE TITLE
Unable to "Create" pizza after uploading S3 version of pizza-luvrs app - seeing 504 Gateway timeout

### ISSUE THREAD

**Issue by smrivera0725** [ryanmurakami/pizza-luvrs#63]
Taking Pluralsight "AWS Developer: Getting Started" class. After completing module 5 "Hosting All the Things with S3" and testing "Create" pizza from load balanced URL, seeing the following 504 in developer tools.  After completing module 4 "Getting Inside the Virtual Machine with EC2 and VPC", pizza luvrs app was working fine locally and on AWS (via load balancer URL).  In doing a little debugging, I found the create pizza ajax call where the app is hanging, again, running pizza luvrs S3 version of the app locally works just fine, and I see my S3 bucket update.

  $.ajax({
    type: 'POST',
    url: '/pizza',
    data: JSON.stringify(pkg),
    contentType: 'application/json charset=utf-8',
    success: function (data) {                                                                                                                                                                                           window.location.assign('/pizza/' + pkg.name.replace(/ /g, '-'))
    }

Request URL: http://pizza-loader-1700948297.us-west-1.elb.amazonaws.com/pizza
Request Method: POST
Status Code: 504 Gateway Time-out
Remote Address: 52.8.22.141:80
Referrer Policy: strict-origin-when-cross-origin
Connection: keep-alive
Content-Length: 534
Content-Type: text/html
Date: Fri, 12 Feb 2021 00:59:33 GMT
Server: awselb/2.0
Set-Cookie: AWSALB=yU5oRl0U1wsHxf77wf4UlhI8K+x/TzFa859tcbodeLixg6cE8I/sswJ2V4WLhsvqkAOeWEn3Y02pPzTT93VIGjeeBKg13HEQhl9belGxINKWbGj/GtxOSgpVtPi2; Expires=Fri, 19 Feb 2021 00:58:33 GMT; Path=/
Set-Cookie: AWSALBCORS=yU5oRl0U1wsHxf77wf4UlhI8K+x/TzFa859tcbodeLixg6cE8I/sswJ2V4WLhsvqkAOeWEn3Y02pPzTT93VIGjeeBKg13HEQhl9belGxINKWbGj/GtxOSgpVtPi2; Expires=Fri, 19 Feb 2021 00:58:33 GMT; Path=/; SameSite=None
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: keep-alive
Content-Length: 226836
Content-Type: application/json charset=UTF-8
Cookie: pzz4lyfe=Fe26.2**2c8e4596418c70182a51dfe9a229ae2ca690f52a6d393232c439ece646d45f0d*EZMepzuTjdlZuE8d7Ozmow*ymId9FykPrEXqMufOHh70BlzlM8iHAJwgH9yiyNNmquZsjUXO5gFvZlCfJinAKms9dtmPS9mg2Y_CAJB3BzzdHQggTjzC-sdoGr_scTgd3wp1BIjcvu16gJ4-vQutM1sX72ir7CmVo2YI8-fRuHa__GZyPtx2LuoncwsMwiscqlG6x0ZSGXyotLBy8DASPZF**de73af48d8249264dc9769e5165a0975f88156335454b4d0b8855f29aafb3ddd*fNYwLhITYBhL6s51i705Pq68R3iD5nMKa6oMx3PMBCs; AWSALB=yi5mtBFDk6yetMVT83o0NKXEXiosSHvRS8Z6xfMS7Scl1xFA393Khgeo3e7q9784NsdcCzHLxwvlzt32bbzlRrPogndlUvmZpO+ereXMDEr58KS0VgNq8uawgj35
Host: pizza-loader-1700948297.us-west-1.elb.amazonaws.com
Origin: http://pizza-loader-1700948297.us-west-1.elb.amazonaws.com
Referer: http://pizza-loader-1700948297.us-west-1.elb.amazonaws.com/make/pizza
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
X-Requested-With: XMLHttpRequest
{toppings: ["dough_crust", "marinara_sauce", "mozzarella_cheese"], username: "stan",…}
img: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAZAA"
name: "dcmsmc pizza"
toppings: ["dough_crust", "marinara_sauce", "mozzarella_cheese"]
username: "stan"

Response:
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

I went through the exercises 2 times from scratch, hoping I had made a mistake, but that didn't help.

Thanks,
Stan

**Comment by ryanmurakami** [comment]
Hi @smrivera0725, we resolved this on the Pluralsight discussions, so I'm closing this issue. Thanks!
