### ISSUE TITLE
NPM 

### ISSUE THREAD

**Issue by progone** [ryanmurakami/pizza-luvrs#7]
[ec2-user@ip-10-0-0-250 pizza-luvrs]$ cat /home/ec2-user/.npm/_logs/2017-05-07T19_25_02_310Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'bugs', 'pizza-luvrs' ]
2 info using npm@4.5.0
3 info using node@v6.10.3
4 silly fetchPackageMetaData pizza-luvrs
5 silly fetchNamedPackageData pizza-luvrs
6 silly mapToRegistry name pizza-luvrs
7 silly mapToRegistry using default registry
8 silly mapToRegistry registry https://registry.npmjs.org/
9 silly mapToRegistry data Result {
9 silly mapToRegistry   raw: 'pizza-luvrs',
9 silly mapToRegistry   scope: null,
9 silly mapToRegistry   escapedName: 'pizza-luvrs',
9 silly mapToRegistry   name: 'pizza-luvrs',
9 silly mapToRegistry   rawSpec: '',
9 silly mapToRegistry   spec: 'latest',
9 silly mapToRegistry   type: 'tag' }
10 silly mapToRegistry uri https://registry.npmjs.org/pizza-luvrs
11 verbose request uri https://registry.npmjs.org/pizza-luvrs
12 verbose request no auth needed
13 info attempt registry request try #1 at 7:25:02 PM
14 verbose request id 08686afb6915a700
15 http request GET https://registry.npmjs.org/pizza-luvrs
16 http 404 https://registry.npmjs.org/pizza-luvrs
17 verbose headers { 'content-type': 'application/json',
17 verbose headers   'cache-control': 'max-age=0',
17 verbose headers   'content-length': '2',
17 verbose headers   'accept-ranges': 'bytes',
17 verbose headers   date: 'Sun, 07 May 2017 19:25:02 GMT',
17 verbose headers   via: '1.1 varnish',
17 verbose headers   age: '0',
17 verbose headers   connection: 'keep-alive',
17 verbose headers   'x-served-by': 'cache-iad2150-IAD',
17 verbose headers   'x-cache': 'MISS',
17 verbose headers   'x-cache-hits': '0',
17 verbose headers   'x-timer': 'S1494185102.223525,VS0,VE71',
17 verbose headers   vary: 'Accept-Encoding' }
18 silly get cb [ 404,
18 silly get   { 'content-type': 'application/json',
18 silly get     'cache-control': 'max-age=0',
18 silly get     'content-length': '2',
18 silly get     'accept-ranges': 'bytes',
18 silly get     date: 'Sun, 07 May 2017 19:25:02 GMT',
18 silly get     via: '1.1 varnish',
18 silly get     age: '0',
18 silly get     connection: 'keep-alive',
18 silly get     'x-served-by': 'cache-iad2150-IAD',
18 silly get     'x-cache': 'MISS',
18 silly get     'x-cache-hits': '0',
18 silly get     'x-timer': 'S1494185102.223525,VS0,VE71',
18 silly get     vary: 'Accept-Encoding' } ]
19 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/pizza-luvrs
19 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:286:14)
19 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
19 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:188:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1171:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1091:12)
19 silly fetchPackageMetaData  error for pizza-luvrs { Error: Registry returned 404 for GET on https://registry.npmjs.org/pizza-luvrs
19 silly fetchPackageMetaData     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:12)
19 silly fetchPackageMetaData     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:286:14)
19 silly fetchPackageMetaData     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
19 silly fetchPackageMetaData     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:188:22)
19 silly fetchPackageMetaData     at emitTwo (events.js:106:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:191:7)
19 silly fetchPackageMetaData     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1171:10)
19 silly fetchPackageMetaData     at emitOne (events.js:96:13)
19 silly fetchPackageMetaData     at Request.emit (events.js:188:7)
19 silly fetchPackageMetaData     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1091:12) pkgid: 'pizza-luvrs', statusCode: 404, code: 'E404' }
20 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/pizza-luvrs
20 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:308:12)
20 verbose stack     at CachingRegistryClient.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:286:14)
20 verbose stack     at Request._callback (/usr/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:216:14)
20 verbose stack     at Request.self.callback (/usr/lib/node_modules/npm/node_modules/request/request.js:188:22)
20 verbose stack     at emitTwo (events.js:106:13)
20 verbose stack     at Request.emit (events.js:191:7)
20 verbose stack     at Request.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1171:10)
20 verbose stack     at emitOne (events.js:96:13)
20 verbose stack     at Request.emit (events.js:188:7)
20 verbose stack     at IncomingMessage.<anonymous> (/usr/lib/node_modules/npm/node_modules/request/request.js:1091:12)
21 verbose statusCode 404
22 verbose pkgid pizza-luvrs
23 verbose cwd /home/ec2-user/pizza-luvrs
24 verbose Linux 4.9.20-11.31.amzn1.x86_64
25 verbose argv "/usr/bin/node" "/usr/bin/npm" "bugs" "pizza-luvrs"
26 verbose node v6.10.3
27 verbose npm  v4.5.0
28 error code E404
29 error 404 Registry returned 404 for GET on https://registry.npmjs.org/pizza-luvrs
30 error 404
31 error 404 'pizza-luvrs' is not in the npm registry.
32 error 404 You should bug the author to publish it (or use the name yourself!)
33 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]

**Comment by ryanmurakami** [comment]
@progone Looks like you're trying to install this using npm. I probably won't be registering it there, so you'll need to just download it directly from Github. 

Thanks for raising the issue!
